import type { Lang } from "@prisma/client";

export const LANGUAGES: Record<Lang, string> = {
  EN: "English",
  ZH: "Mandarin Chinese",
  HI: "Hindi",
  ES: "Spanish",
  FR: "French",
  AR: "Modern Standard Arabic",
  BN: "Bengali",
  RU: "Russian",
  PT: "Portuguese",
  ID: "Indonesian",
  UR: "Urdu",
  DE: "German",
  JA: "Japanese",
  SW: "Swahili",
  MR: "Marathi",
  TE: "Telugu",
  TR: "Turkish",
  TA: "Tamil",
  FA: "Persian",
  IT: "Italian",
  TH: "Thai",
  GU: "Gujarati",
  KN: "Kannada",
  KO: "Korean",
  PL: "Polish",
  PA: "Punjabi",
  VI: "Vietnamese",
  NL: "Dutch",
  SV: "Swedish",
  RO: "Romanian"
};